// Writes lib/features/game/presentation/scene_strip/village_svg.dart from the
// Claude Design handoff: the five villages of the scene strip (15g–15k), as
// the prototype's own stop-scenes.js draws them.
//
//   node tool/village_scenes.js <handoff project dir>
//
// The prototype builds each scene as SVG markup from its shape makers; this
// runs those makers as they are and keeps the markup, which the game reads
// with a small parser (see `buildVillage`). Regenerate when the handoff
// changes rather than editing the output.
const fs = require('fs');
const path = require('path');

const dir = process.argv[2];
if (!dir) throw new Error('usage: node tool/village_scenes.js <handoff project dir>');

global.window = globalThis;
global.document = { createElementNS() { return {}; }, visibilityState: 'visible' };
eval(fs.readFileSync(path.join(dir, 'forest-strip.js'), 'utf8'));
const src = fs
  .readFileSync(path.join(dir, 'stop-scenes.js'), 'utf8')
  .replace('window.StopScenes = { mount };', 'window.StopScenes = { mount, villages2 };');
eval(src);

const biomes = ['forest', 'mountains', 'coast', 'desert', 'floodlands'];
let out = `// GENERATED by tool/village_scenes.js from the Claude Design handoff
// (stop-scenes.js, villages 15g–15k). Do not edit by hand.

/// Each biome's village on the scene strip, as the prototype's SVG markup:
/// the scene's body, drawn over its own sky, gradients named with the id
/// \`v\` (\`url(#vw)\` the warm glow, \`#vfog\`, \`#vwat\`, \`#vws\`).
const Map<String, String> kVillageSvg = {
`;
for (const b of biomes) {
  const svg = window.StopScenes.villages2[b]('v');
  if (svg.includes("'''")) throw new Error('markup would end the raw string');
  out += `  '${b}': r'''${svg}''',\n`;
}
out += '};\n';
const target = path.join(__dirname, '..', 'lib', 'features', 'game', 'presentation', 'scene_strip', 'village_svg.dart');
fs.writeFileSync(target, out);
console.log('wrote', target);
